# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

minecraft_version=1.21.3
minecraft_version_range=[1.21.3,1.22)
forge_version=53.1.0
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.21.3

## Mod Properties

mod_id=chunkeffects
mod_name=Random Effects
mod_license=All Rights Reserved
mod_version=1.0.4
mod_group_id=net.bagaja
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=BaGaJa
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Every Chunk has a now a random effect so be careful where you step.